### ISSUE TITLE
loosing session ?

### ISSUE THREAD

**Issue by Alex-1963** [mgp25/WhatsApp-Tracker#7]
Hi there,

when i'm track my number with
```
E:\PHP>php.exe -f "E:\inetpub\wa\watracker.php" -- -cHidden 491#########
```
in a CMD Window, i get results for some time (~10 min) but then it track no longer. Is this an issue with a session state and what can i do?
I'm using it on an IIS6 server with PHP extension

Regards, Alex

**Comment by mgp25** [comment]
Use the same script but update the src folder with the one you can find in WhatsAPI Official. That should fix this issue.

https://github.com/mgp25/WhatsAPI-Official

Regards.
